# Generated by Django 4.0.5 on 2022-06-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=500)),
                ('work_address', models.CharField(max_length=500)),
                ('postal_address', models.CharField(max_length=500)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.people')),
            ],
        ),
    ]
