# Generated by Django 4.0.5 on 2022-06-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.TextField()),
            ],
        ),
    ]
