# Generated by Django 4.0.5 on 2022-06-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('bio_sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appone.people')),
            ],
        ),
    ]
